export const academicTemplate = {
  version: "5.3.0",
  objects: [
    // Academic background
    {
      type: "rect",
      left: 0,
      top: 0,
      width: 800,
      height: 566,
      fill: "#fefefe",
    },
    // University-style header
    {
      type: "rect",
      left: 0,
      top: 0,
      width: 800,
      height: 80,
      fill: "#1e40af",
    },
    {
      type: "rect",
      left: 0,
      top: 80,
      width: 800,
      height: 4,
      fill: "#dc2626",
    },
    // University shield placeholder
    {
      type: "rect",
      left: 50,
      top: 20,
      width: 40,
      height: 40,
      fill: "#ffffff",
      opacity: 0.9,
    },
    {
      type: "triangle",
      left: 65,
      top: 25,
      width: 10,
      height: 15,
      fill: "#1e40af",
    },
    // University name
    {
      type: "textbox",
      originX: "left",
      left: 110,
      top: 25,
      width: 400,
      fill: "#ffffff",
      text: "UNIVERSITY OF EXCELLENCE",
      fontSize: 16,
      fontWeight: "700",
      fontFamily: "Times New Roman",
      textAlign: "left",
      letterSpacing: 2,
    },
    {
      type: "textbox",
      originX: "left",
      left: 110,
      top: 45,
      width: 400,
      fill: "#dbeafe",
      text: "Established 1875 • Academic Excellence",
      fontSize: 12,
      fontFamily: "Times New Roman",
      textAlign: "left",
    },
    // Academic certificate title
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 110,
      width: 650,
      fill: "#1e40af",
      text: "CERTIFICATE",
      fontSize: 42,
      fontWeight: "400",
      fontFamily: "Times New Roman",
      textAlign: "center",
      letterSpacing: 8,
    },
    // Academic subtitle
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 155,
      width: 500,
      fill: "#dc2626",
      text: "of Academic Achievement",
      fontSize: 22,
      fontWeight: "400",
      fontFamily: "Times New Roman",
      textAlign: "center",
      letterSpacing: 1,
    },
    // Academic decoration
    {
      type: "rect",
      left: 325,
      top: 185,
      width: 150,
      height: 1,
      fill: "#1e40af",
    },
    {
      type: "rect",
      left: 385,
      top: 182,
      width: 30,
      height: 7,
      fill: "#dc2626",
    },
    // Latin phrase
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 205,
      width: 400,
      fill: "#374151",
      text: "Universitas magistrorum et scholarium",
      fontSize: 14,
      fontFamily: "Times New Roman",
      textAlign: "center",
      fontStyle: "italic",
    },
    // Formal presentation
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 230,
      width: 400,
      fill: "#1f2937",
      text: "Be it known that",
      fontSize: 16,
      fontFamily: "Times New Roman",
      textAlign: "center",
    },
    // Recipient name
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 260,
      width: 600,
      fill: "#1e40af",
      text: "RECIPIENT NAME",
      fontSize: 36,
      fontWeight: "bold",
      fontFamily: "Times New Roman",
      textAlign: "center",
      letterSpacing: 1,
    },
    // Academic underline
    {
      type: "rect",
      left: 200,
      top: 305,
      width: 400,
      height: 2,
      fill: "#dc2626",
    },
    // Academic achievement
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 325,
      width: 650,
      fill: "#1f2937",
      text: "having fulfilled all requirements has been awarded this",
      fontSize: 16,
      fontFamily: "Times New Roman",
      textAlign: "center",
    },
    // Degree/Program name
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 355,
      width: 600,
      fill: "#1e40af",
      text: "Master Certificate in Data Science",
      fontSize: 26,
      fontWeight: "bold",
      fontFamily: "Times New Roman",
      textAlign: "center",
    },
    // Academic honors
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 385,
      width: 400,
      fill: "#dc2626",
      text: "Magna Cum Laude",
      fontSize: 18,
      fontWeight: "500",
      fontFamily: "Times New Roman",
      textAlign: "center",
      fontStyle: "italic",
    },
    // Academic details
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 410,
      width: 500,
      fill: "#6b7280",
      text: "with all the rights and privileges pertaining thereto",
      fontSize: 14,
      fontFamily: "Times New Roman",
      textAlign: "center",
      fontStyle: "italic",
    },
    // Date section
    {
      type: "textbox",
      originX: "left",
      left: 100,
      top: 460,
      width: 200,
      fill: "#6b7280",
      text: "Conferred this",
      fontSize: 14,
      fontFamily: "Times New Roman",
      textAlign: "left",
      fontStyle: "italic",
    },
    {
      type: "textbox",
      originX: "left",
      left: 100,
      top: 480,
      width: 200,
      fill: "#1f2937",
      text: "15th day of March",
      fontSize: 16,
      fontWeight: "500",
      fontFamily: "Times New Roman",
      textAlign: "left",
    },
    {
      type: "textbox",
      originX: "left",
      left: 100,
      top: 500,
      width: 200,
      fill: "#1f2937",
      text: "Year 2024",
      fontSize: 16,
      fontWeight: "500",
      fontFamily: "Times New Roman",
      textAlign: "left",
    },
    // Academic seal
    {
      type: "circle",
      left: 550,
      top: 470,
      radius: 40,
      fill: "transparent",
      stroke: "#1e40af",
      strokeWidth: 3,
    },
    {
      type: "circle",
      left: 550,
      top: 470,
      radius: 30,
      fill: "transparent",
      stroke: "#dc2626",
      strokeWidth: 2,
    },
    {
      type: "textbox",
      originX: "center",
      left: 590,
      top: 455,
      width: 80,
      fill: "#1e40af",
      text: "UNIVERSITY",
      fontSize: 9,
      fontWeight: "bold",
      fontFamily: "Times New Roman",
      textAlign: "center",
    },
    {
      type: "textbox",
      originX: "center",
      left: 590,
      top: 470,
      width: 80,
      fill: "#dc2626",
      text: "SEAL",
      fontSize: 12,
      fontWeight: "bold",
      fontFamily: "Times New Roman",
      textAlign: "center",
    },
    {
      type: "textbox",
      originX: "center",
      left: 590,
      top: 485,
      width: 80,
      fill: "#1e40af",
      text: "2024",
      fontSize: 10,
      fontWeight: "bold",
      fontFamily: "Times New Roman",
      textAlign: "center",
    },
    // Dean signature
    {
      type: "line",
      x1: 0,
      y1: 0,
      x2: 140,
      y2: 0,
      left: 630,
      top: 530,
      stroke: "#1e40af",
      strokeWidth: 1,
    },
    {
      type: "textbox",
      originX: "center",
      left: 700,
      top: 540,
      width: 140,
      fill: "#374151",
      text: "Dean of Academic Affairs",
      fontSize: 11,
      fontFamily: "Times New Roman",
      textAlign: "center",
    },
    // Registrar signature
    {
      type: "line",
      x1: 0,
      y1: 0,
      x2: 140,
      y2: 0,
      left: 300,
      top: 530,
      stroke: "#1e40af",
      strokeWidth: 1,
    },
    {
      type: "textbox",
      originX: "center",
      left: 370,
      top: 540,
      width: 140,
      fill: "#374151",
      text: "Registrar",
      fontSize: 11,
      fontFamily: "Times New Roman",
      textAlign: "center",
    },
  ],
  background: "#ffffff",
};
