export const achievementTemplate = {
  version: "5.3.0",
  objects: [
    // Achievement banner
    {
      type: "rect",
      left: 0,
      top: 40,
      width: 800,
      height: 120,
      fill: "#0ea5e9",
      opacity: 0.1,
    },
    // Success elements
    {
      type: "circle",
      left: 70,
      top: 70,
      radius: 20,
      fill: "#10b981",
      opacity: 0.3,
    },
    {
      type: "circle",
      left: 710,
      top: 70,
      radius: 20,
      fill: "#f59e0b",
      opacity: 0.3,
    },
    {
      type: "circle",
      left: 70,
      top: 450,
      radius: 15,
      fill: "#8b5cf6",
      opacity: 0.3,
    },
    {
      type: "circle",
      left: 710,
      top: 450,
      radius: 15,
      fill: "#ef4444",
      opacity: 0.3,
    },
    // Star achievement symbols
    {
      type: "triangle",
      left: 120,
      top: 120,
      width: 12,
      height: 12,
      fill: "#fbbf24",
      angle: 0,
    },
    {
      type: "triangle",
      left: 660,
      top: 120,
      width: 12,
      height: 12,
      fill: "#06b6d4",
      angle: 180,
    },
    // Achievement title
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 80,
      width: 650,
      fill: "#0c4a6e",
      text: "ACHIEVEMENT",
      fontSize: 44,
      fontWeight: "800",
      fontFamily: "Arial",
      textAlign: "center",
      letterSpacing: 10,
    },
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 130,
      width: 650,
      fill: "#0284c7",
      text: "CERTIFICATE",
      fontSize: 32,
      fontWeight: "400",
      fontFamily: "Arial",
      textAlign: "center",
      letterSpacing: 6,
    },
    // Dynamic accent line
    {
      type: "rect",
      left: 250,
      top: 175,
      width: 300,
      height: 4,
      fill: "#0ea5e9",
    },
    {
      type: "rect",
      left: 280,
      top: 172,
      width: 60,
      height: 10,
      fill: "#10b981",
      opacity: 0.8,
    },
    {
      type: "rect",
      left: 460,
      top: 172,
      width: 60,
      height: 10,
      fill: "#f59e0b",
      opacity: 0.8,
    },
    // Recognition text
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 200,
      width: 400,
      fill: "#075985",
      text: "This recognizes the outstanding achievement of",
      fontSize: 16,
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Recipient name with achievement styling
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 230,
      width: 600,
      fill: "#0c4a6e",
      text: "RECIPIENT NAME",
      fontSize: 38,
      fontWeight: "700",
      fontFamily: "Arial",
      textAlign: "center",
      letterSpacing: 2,
    },
    // Achievement underline with medals
    {
      type: "rect",
      left: 180,
      top: 275,
      width: 440,
      height: 3,
      fill: "#0ea5e9",
    },
    {
      type: "circle",
      left: 175,
      top: 272,
      radius: 5,
      fill: "#fbbf24",
    },
    {
      type: "circle",
      left: 621,
      top: 272,
      radius: 5,
      fill: "#fbbf24",
    },
    // Achievement description
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 300,
      width: 650,
      fill: "#075985",
      text: "who has demonstrated exceptional performance and successfully achieved",
      fontSize: 16,
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Achievement name
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 330,
      width: 600,
      fill: "#0c4a6e",
      text: "Excellence in Innovation & Leadership",
      fontSize: 26,
      fontWeight: "600",
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Achievement metrics
    {
      type: "rect",
      left: 200,
      top: 370,
      width: 400,
      height: 40,
      fill: "#f0f9ff",
      stroke: "#0ea5e9",
      strokeWidth: 1,
    },
    {
      type: "textbox",
      originX: "center",
      left: 300,
      top: 378,
      width: 100,
      fill: "#10b981",
      text: "98% Score",
      fontSize: 12,
      fontWeight: "600",
      fontFamily: "Arial",
      textAlign: "center",
    },
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 378,
      width: 100,
      fill: "#f59e0b",
      text: "Top 5%",
      fontSize: 12,
      fontWeight: "600",
      fontFamily: "Arial",
      textAlign: "center",
    },
    {
      type: "textbox",
      originX: "center",
      left: 500,
      top: 378,
      width: 100,
      fill: "#8b5cf6",
      text: "Gold Level",
      fontSize: 12,
      fontWeight: "600",
      fontFamily: "Arial",
      textAlign: "center",
    },
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 390,
      width: 400,
      fill: "#0284c7",
      text: "Outstanding Achievement Recognition",
      fontSize: 12,
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Date and credentials
    {
      type: "textbox",
      originX: "left",
      left: 80,
      top: 450,
      width: 200,
      fill: "#6b7280",
      text: "ACHIEVEMENT DATE",
      fontSize: 12,
      fontWeight: "600",
      fontFamily: "Arial",
      textAlign: "left",
      letterSpacing: 1,
    },
    {
      type: "textbox",
      originX: "left",
      left: 80,
      top: 470,
      width: 200,
      fill: "#0c4a6e",
      text: "March 15, 2024",
      fontSize: 16,
      fontWeight: "500",
      fontFamily: "Arial",
      textAlign: "left",
    },
    // Achievement ID
    {
      type: "textbox",
      originX: "right",
      left: 720,
      top: 450,
      width: 200,
      fill: "#6b7280",
      text: "ACHIEVEMENT ID",
      fontSize: 12,
      fontWeight: "600",
      fontFamily: "Arial",
      textAlign: "right",
      letterSpacing: 1,
    },
    {
      type: "textbox",
      originX: "right",
      left: 720,
      top: 470,
      width: 200,
      fill: "#0c4a6e",
      text: "ACH-2024-0789",
      fontSize: 16,
      fontWeight: "500",
      fontFamily: "Arial",
      textAlign: "right",
    },
    // Authority signature
    {
      type: "line",
      x1: 0,
      y1: 0,
      x2: 160,
      y2: 0,
      left: 320,
      top: 510,
      stroke: "#0ea5e9",
      strokeWidth: 2,
    },
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 520,
      width: 160,
      fill: "#075985",
      text: "Achievement Council",
      fontSize: 13,
      fontWeight: "500",
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Success badge
    {
      type: "rect",
      left: 350,
      top: 540,
      width: 100,
      height: 20,
      fill: "#10b981",
    },
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 543,
      width: 100,
      fill: "#ffffff",
      text: "VERIFIED SUCCESS",
      fontSize: 9,
      fontWeight: "600",
      fontFamily: "Arial",
      textAlign: "center",
    },
  ],
  background: "#f0f9ff",
};
