export const artisticTemplate = {
  version: "5.3.0",
  objects: [
    // Paint splash effects
    {
      type: "circle",
      left: 100,
      top: 60,
      radius: 45,
      fill: "#ff6b6b",
      opacity: 0.15,
    },
    {
      type: "circle",
      left: 85,
      top: 75,
      radius: 25,
      fill: "#4ecdc4",
      opacity: 0.2,
    },
    {
      type: "circle",
      left: 680,
      top: 80,
      radius: 35,
      fill: "#45b7d1",
      opacity: 0.18,
    },
    {
      type: "circle",
      left: 700,
      top: 450,
      radius: 40,
      fill: "#96ceb4",
      opacity: 0.15,
    },
    {
      type: "circle",
      left: 120,
      top: 480,
      radius: 30,
      fill: "#ffeaa7",
      opacity: 0.2,
    },
    // Brush stroke decorations
    {
      type: "rect",
      left: 50,
      top: 30,
      width: 200,
      height: 12,
      fill: "#ff7675",
      opacity: 0.3,
      angle: 15,
    },
    {
      type: "rect",
      left: 550,
      top: 520,
      width: 180,
      height: 10,
      fill: "#74b9ff",
      opacity: 0.3,
      angle: -10,
    },
    // Artistic frame
    {
      type: "rect",
      left: 30,
      top: 30,
      width: 740,
      height: 506,
      fill: "transparent",
      stroke: "#dda15e",
      strokeWidth: 3,
      strokeDashArray: [15, 5],
    },
    // Paint palette colors
    {
      type: "circle",
      left: 750,
      top: 40,
      radius: 8,
      fill: "#ff6b6b",
    },
    {
      type: "circle",
      left: 730,
      top: 55,
      radius: 6,
      fill: "#4ecdc4",
    },
    {
      type: "circle",
      left: 765,
      top: 60,
      radius: 7,
      fill: "#45b7d1",
    },
    // Artistic title
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 80,
      width: 650,
      fill: "#e17055",
      text: "ARTISTIC",
      fontSize: 40,
      fontWeight: "700",
      fontFamily: "Arial",
      textAlign: "center",
      letterSpacing: 6,
      angle: -1,
    },
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 125,
      width: 650,
      fill: "#6c5ce7",
      text: "CERTIFICATE",
      fontSize: 40,
      fontWeight: "300",
      fontFamily: "Arial",
      textAlign: "center",
      letterSpacing: 6,
      angle: 1,
    },
    // Creative subtitle
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 170,
      width: 500,
      fill: "#fd79a8",
      text: "~ Creative Excellence Award ~",
      fontSize: 18,
      fontWeight: "400",
      fontFamily: "Arial",
      textAlign: "center",
      fontStyle: "italic",
      letterSpacing: 2,
    },
    // Artistic divider
    {
      type: "ellipse",
      left: 350,
      top: 198,
      rx: 50,
      ry: 5,
      fill: "#fdcb6e",
      opacity: 0.6,
    },
    // Recognition text
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 220,
      width: 400,
      fill: "#2d3436",
      text: "This celebrates the artistic talent of",
      fontSize: 16,
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Artist name
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 250,
      width: 600,
      fill: "#e17055",
      text: "RECIPIENT NAME",
      fontSize: 36,
      fontWeight: "600",
      fontFamily: "Arial",
      textAlign: "center",
      letterSpacing: 2,
    },
    // Colorful underline
    {
      type: "rect",
      left: 180,
      top: 295,
      width: 110,
      height: 3,
      fill: "#ff6b6b",
    },
    {
      type: "rect",
      left: 300,
      top: 295,
      width: 110,
      height: 3,
      fill: "#4ecdc4",
    },
    {
      type: "rect",
      left: 420,
      top: 295,
      width: 110,
      height: 3,
      fill: "#45b7d1",
    },
    {
      type: "rect",
      left: 540,
      top: 295,
      width: 80,
      height: 3,
      fill: "#96ceb4",
    },
    // Artistic achievement text
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 320,
      width: 650,
      fill: "#2d3436",
      text: "for exceptional creativity and mastery in",
      fontSize: 16,
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Artistic program
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 350,
      width: 600,
      fill: "#6c5ce7",
      text: "Digital Arts & Creative Design",
      fontSize: 24,
      fontWeight: "600",
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Creative skills showcase
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 380,
      width: 550,
      fill: "#fd79a8",
      text: "Visual Arts • Creative Thinking • Digital Mastery",
      fontSize: 14,
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Artistic date section
    {
      type: "triangle",
      left: 75,
      top: 430,
      width: 20,
      height: 20,
      fill: "#fdcb6e",
      opacity: 0.6,
    },
    {
      type: "textbox",
      originX: "left",
      left: 110,
      top: 435,
      width: 200,
      fill: "#636e72",
      text: "Created on",
      fontSize: 14,
      fontFamily: "Arial",
      textAlign: "left",
      fontStyle: "italic",
    },
    {
      type: "textbox",
      originX: "left",
      left: 110,
      top: 455,
      width: 200,
      fill: "#2d3436",
      text: "March 15, 2024",
      fontSize: 16,
      fontWeight: "500",
      fontFamily: "Arial",
      textAlign: "left",
    },
    // Artistic ID
    {
      type: "circle",
      left: 695,
      top: 430,
      radius: 10,
      fill: "#a29bfe",
      opacity: 0.6,
    },
    {
      type: "textbox",
      originX: "right",
      left: 690,
      top: 435,
      width: 200,
      fill: "#636e72",
      text: "Artwork ID",
      fontSize: 14,
      fontFamily: "Arial",
      textAlign: "right",
      fontStyle: "italic",
    },
    {
      type: "textbox",
      originX: "right",
      left: 690,
      top: 455,
      width: 200,
      fill: "#2d3436",
      text: "ART-2024-0123",
      fontSize: 16,
      fontWeight: "500",
      fontFamily: "Arial",
      textAlign: "right",
    },
    // Artist signature
    {
      type: "rect",
      left: 300,
      top: 500,
      width: 200,
      height: 25,
      fill: "transparent",
      stroke: "#e17055",
      strokeWidth: 2,
      strokeDashArray: [8, 4],
    },
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 505,
      width: 200,
      fill: "#e17055",
      text: "Master Artist & Instructor",
      fontSize: 12,
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Paint brush signature
    {
      type: "line",
      x1: 0,
      y1: 0,
      x2: 40,
      y2: 0,
      left: 520,
      top: 535,
      stroke: "#dda15e",
      strokeWidth: 3,
    },
    {
      type: "circle",
      left: 555,
      top: 532,
      radius: 4,
      fill: "#e17055",
    },
  ],
  background: "#fffbf0",
};
