export const classicTemplate = {
  version: "5.3.0",
  objects: [
    // Decorative border
    {
      type: "rect",
      left: 30,
      top: 30,
      width: 740,
      height: 506,
      fill: "transparent",
      stroke: "#8B4513",
      strokeWidth: 4,
    },
    {
      type: "rect",
      left: 40,
      top: 40,
      width: 720,
      height: 486,
      fill: "transparent",
      stroke: "#8B4513",
      strokeWidth: 2,
    },
    // Header decoration
    {
      type: "rect",
      left: 60,
      top: 70,
      width: 680,
      height: 3,
      fill: "#D4AF37",
    },
    // Title
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 85,
      width: 650,
      fill: "#8B4513",
      text: "Certificate of Excellence",
      fontSize: 48,
      fontFamily: "Times New Roman",
      textAlign: "center",
      fontWeight: "bold",
    },
    // Subtitle
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 140,
      width: 600,
      fill: "#654321",
      text: "This is to certify that",
      fontSize: 18,
      fontFamily: "Times New Roman",
      textAlign: "center",
      fontStyle: "italic",
    },
    // Student name
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 170,
      width: 600,
      fill: "#2C1810",
      text: "STUDENT NAME",
      fontSize: 42,
      fontWeight: "bold",
      fontFamily: "Times New Roman",
      textAlign: "center",
      textDecoration: "underline",
    },
    // Course description
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 230,
      width: 650,
      fill: "#654321",
      text: "has successfully completed the comprehensive course",
      fontSize: 18,
      fontFamily: "Times New Roman",
      textAlign: "center",
    },
    // Course name
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 260,
      width: 600,
      fill: "#8B4513",
      text: "Web Development Fundamentals",
      fontSize: 28,
      fontWeight: "bold",
      fontFamily: "Times New Roman",
      textAlign: "center",
      fontStyle: "italic",
    },
    // Achievement text
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 300,
      width: 650,
      fill: "#654321",
      text: "demonstrating proficiency and dedication in the subject matter",
      fontSize: 16,
      fontFamily: "Times New Roman",
      textAlign: "center",
    },
    // Date label
    {
      type: "textbox",
      originX: "left",
      left: 120,
      top: 380,
      width: 200,
      fill: "#654321",
      text: "Date of Completion:",
      fontSize: 16,
      fontFamily: "Times New Roman",
      textAlign: "left",
    },
    // Date value
    {
      type: "textbox",
      originX: "left",
      left: 120,
      top: 405,
      width: 200,
      fill: "#2C1810",
      text: "January 15, 2024",
      fontSize: 16,
      fontFamily: "Times New Roman",
      textAlign: "left",
      fontWeight: "bold",
    },
    // Certificate ID
    {
      type: "textbox",
      originX: "right",
      left: 680,
      top: 380,
      width: 200,
      fill: "#654321",
      text: "Certificate ID:",
      fontSize: 16,
      fontFamily: "Times New Roman",
      textAlign: "right",
    },
    // Certificate ID value
    {
      type: "textbox",
      originX: "right",
      left: 680,
      top: 405,
      width: 200,
      fill: "#2C1810",
      text: "CRT-2024-001",
      fontSize: 16,
      fontFamily: "Times New Roman",
      textAlign: "right",
      fontWeight: "bold",
    },
    // Signature lines
    {
      type: "line",
      x1: 0,
      y1: 0,
      x2: 150,
      y2: 0,
      left: 150,
      top: 470,
      stroke: "#8B4513",
      strokeWidth: 2,
    },
    {
      type: "line",
      x1: 0,
      y1: 0,
      x2: 150,
      y2: 0,
      left: 500,
      top: 470,
      stroke: "#8B4513",
      strokeWidth: 2,
    },
    // Signature labels
    {
      type: "textbox",
      originX: "center",
      left: 225,
      top: 480,
      width: 150,
      fill: "#654321",
      text: "Director",
      fontSize: 14,
      fontFamily: "Times New Roman",
      textAlign: "center",
    },
    {
      type: "textbox",
      originX: "center",
      left: 575,
      top: 480,
      width: 150,
      fill: "#654321",
      text: "Instructor",
      fontSize: 14,
      fontFamily: "Times New Roman",
      textAlign: "center",
    },
    // Footer decoration
    {
      type: "rect",
      left: 60,
      top: 510,
      width: 680,
      height: 3,
      fill: "#D4AF37",
    },
  ],
  background: "#FFF8DC",
};
