export const classicTemplate = {
  version: "5.3.0",
  objects: [
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 60,
      width: 600,
      fill: "#c0392b",
      text: "Certificate of Completion",
      fontSize: 70,
      fontFamily: "Times New Roman",
      textAlign: "center",
      fontStyle: "italic",
    },
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 220,
      width: 600,
      fill: "#2c3e50",
      text: "This certifies that",
      fontSize: 20,
      fontFamily: "Georgia",
      textAlign: "center",
    },
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 270,
      width: 600,
      fill: "#2c3e50",
      text: "STUDENT'S NAME",
      fontSize: 60,
      fontWeight: "bold",
      fontFamily: "Georgia",
      textAlign: "center",
    },
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 380,
      width: 600,
      fill: "#2c3e50",
      text: "has successfully completed the course on Web Development.",
      fontSize: 20,
      fontFamily: "Georgia",
      textAlign: "center",
    },
  ],
  background: "#fdf5e6",
};
