export const corporateTemplate = {
  version: "5.3.0",
  objects: [
    // Header section with gradient effect
    {
      type: "rect",
      left: 0,
      top: 0,
      width: 800,
      height: 120,
      fill: "#1e293b",
    },
    {
      type: "rect",
      left: 0,
      top: 120,
      width: 800,
      height: 20,
      fill: "#334155",
      opacity: 0.3,
    },
    // Company logo placeholder
    {
      type: "rect",
      left: 50,
      top: 40,
      width: 60,
      height: 40,
      fill: "#ffffff",
      opacity: 0.1,
      stroke: "#ffffff",
      strokeWidth: 1,
    },
    {
      type: "textbox",
      originX: "left",
      left: 125,
      top: 45,
      width: 300,
      fill: "#ffffff",
      text: "CORPORATE ACADEMY",
      fontSize: 18,
      fontWeight: "600",
      fontFamily: "Arial",
      textAlign: "left",
      letterSpacing: 2,
    },
    {
      type: "textbox",
      originX: "left",
      left: 125,
      top: 70,
      width: 300,
      fill: "#cbd5e1",
      text: "Excellence in Professional Development",
      fontSize: 12,
      fontFamily: "Arial",
      textAlign: "left",
    },
    // Main certificate title
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 160,
      width: 600,
      fill: "#1e293b",
      text: "CERTIFICATE OF COMPLETION",
      fontSize: 36,
      fontWeight: "700",
      fontFamily: "Arial",
      textAlign: "center",
      letterSpacing: 4,
    },
    // Presented to section
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 210,
      width: 400,
      fill: "#475569",
      text: "This is to certify that",
      fontSize: 16,
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Recipient name
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 240,
      width: 600,
      fill: "#1e293b",
      text: "RECIPIENT NAME",
      fontSize: 32,
      fontWeight: "600",
      fontFamily: "Arial",
      textAlign: "center",
      letterSpacing: 1,
    },
    // Professional underline
    {
      type: "rect",
      left: 225,
      top: 280,
      width: 350,
      height: 2,
      fill: "#3b82f6",
    },
    // Achievement description
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 300,
      width: 650,
      fill: "#475569",
      text: "has successfully demonstrated competency and completed all requirements for",
      fontSize: 15,
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Program name
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 330,
      width: 600,
      fill: "#1e293b",
      text: "Executive Leadership Certificate Program",
      fontSize: 22,
      fontWeight: "600",
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Program details
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 365,
      width: 500,
      fill: "#64748b",
      text: "120 Hours • 8 Modules • Capstone Project",
      fontSize: 13,
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Footer section
    {
      type: "rect",
      left: 0,
      top: 446,
      width: 800,
      height: 120,
      fill: "#f1f5f9",
    },
    // Date section
    {
      type: "textbox",
      originX: "left",
      left: 80,
      top: 470,
      width: 150,
      fill: "#64748b",
      text: "COMPLETION DATE",
      fontSize: 11,
      fontWeight: "600",
      fontFamily: "Arial",
      textAlign: "left",
      letterSpacing: 1,
    },
    {
      type: "textbox",
      originX: "left",
      left: 80,
      top: 485,
      width: 150,
      fill: "#1e293b",
      text: "March 15, 2024",
      fontSize: 14,
      fontWeight: "500",
      fontFamily: "Arial",
      textAlign: "left",
    },
    // Certificate ID
    {
      type: "textbox",
      originX: "right",
      left: 720,
      top: 470,
      width: 150,
      fill: "#64748b",
      text: "CERTIFICATE ID",
      fontSize: 11,
      fontWeight: "600",
      fontFamily: "Arial",
      textAlign: "right",
      letterSpacing: 1,
    },
    {
      type: "textbox",
      originX: "right",
      left: 720,
      top: 485,
      width: 150,
      fill: "#1e293b",
      text: "CRP-2024-0567",
      fontSize: 14,
      fontWeight: "500",
      fontFamily: "Arial",
      textAlign: "right",
    },
    // Signature section
    {
      type: "line",
      x1: 0,
      y1: 0,
      x2: 140,
      y2: 0,
      left: 330,
      top: 520,
      stroke: "#64748b",
      strokeWidth: 1,
    },
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 530,
      width: 140,
      fill: "#64748b",
      text: "Chief Executive Officer",
      fontSize: 12,
      fontFamily: "Arial",
      textAlign: "center",
    },
  ],
  background: "#ffffff",
};
