export const creativeTemplate = {
  version: "5.3.0",
  objects: [
    // Artistic color blocks
    {
      type: "rect",
      left: 0,
      top: 0,
      width: 150,
      height: 566,
      fill: "#fb923c",
      opacity: 0.1,
    },
    {
      type: "rect",
      left: 650,
      top: 0,
      width: 150,
      height: 566,
      fill: "#8b5cf6",
      opacity: 0.1,
    },
    // Diagonal accent
    {
      type: "rect",
      left: 100,
      top: 30,
      width: 600,
      height: 8,
      fill: "#f97316",
      angle: 2,
    },
    // Creative circles
    {
      type: "circle",
      left: 120,
      top: 80,
      radius: 35,
      fill: "#fbbf24",
      opacity: 0.2,
    },
    {
      type: "circle",
      left: 650,
      top: 450,
      radius: 40,
      fill: "#a855f7",
      opacity: 0.15,
    },
    {
      type: "circle",
      left: 700,
      top: 120,
      radius: 25,
      fill: "#06b6d4",
      opacity: 0.2,
    },
    // Artistic title
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 70,
      width: 600,
      fill: "#ea580c",
      text: "CREATIVE",
      fontSize: 46,
      fontWeight: "800",
      fontFamily: "Arial",
      textAlign: "center",
      letterSpacing: 8,
    },
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 120,
      width: 600,
      fill: "#7c3aed",
      text: "CERTIFICATE",
      fontSize: 46,
      fontWeight: "300",
      fontFamily: "Arial",
      textAlign: "center",
      letterSpacing: 8,
    },
    // Creative subtitle
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 170,
      width: 500,
      fill: "#0891b2",
      text: "~ Innovation & Artistry ~",
      fontSize: 18,
      fontWeight: "400",
      fontFamily: "Arial",
      textAlign: "center",
      fontStyle: "italic",
      letterSpacing: 2,
    },
    // Artistic flourish
    {
      type: "triangle",
      left: 360,
      top: 200,
      width: 15,
      height: 15,
      fill: "#f97316",
      angle: 30,
    },
    {
      type: "triangle",
      left: 425,
      top: 200,
      width: 15,
      height: 15,
      fill: "#a855f7",
      angle: -30,
    },
    // Achievement text
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 230,
      width: 400,
      fill: "#451a03",
      text: "This recognizes",
      fontSize: 16,
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Recipient name with creative styling
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 260,
      width: 600,
      fill: "#ea580c",
      text: "RECIPIENT NAME",
      fontSize: 34,
      fontWeight: "700",
      fontFamily: "Arial",
      textAlign: "center",
      letterSpacing: 2,
    },
    // Creative underline elements
    {
      type: "rect",
      left: 200,
      top: 305,
      width: 120,
      height: 3,
      fill: "#f97316",
    },
    {
      type: "rect",
      left: 340,
      top: 305,
      width: 120,
      height: 3,
      fill: "#a855f7",
    },
    {
      type: "rect",
      left: 480,
      top: 305,
      width: 120,
      height: 3,
      fill: "#06b6d4",
    },
    // Achievement description
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 330,
      width: 650,
      fill: "#451a03",
      text: "for exceptional creativity and successful completion of",
      fontSize: 16,
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Program name
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 360,
      width: 600,
      fill: "#7c3aed",
      text: "Creative Design Mastery Course",
      fontSize: 24,
      fontWeight: "600",
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Creative skills
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 390,
      width: 550,
      fill: "#0891b2",
      text: "Digital Art • UI/UX Design • Creative Thinking",
      fontSize: 14,
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Artistic date section
    {
      type: "rect",
      left: 70,
      top: 440,
      width: 80,
      height: 2,
      fill: "#f97316",
    },
    {
      type: "textbox",
      originX: "left",
      left: 80,
      top: 450,
      width: 200,
      fill: "#451a03",
      text: "Completed: March 15, 2024",
      fontSize: 14,
      fontWeight: "500",
      fontFamily: "Arial",
      textAlign: "left",
    },
    // Creative ID section
    {
      type: "rect",
      left: 650,
      top: 440,
      width: 80,
      height: 2,
      fill: "#a855f7",
    },
    {
      type: "textbox",
      originX: "right",
      left: 720,
      top: 450,
      width: 200,
      fill: "#451a03",
      text: "ID: CRE-2024-0456",
      fontSize: 14,
      fontWeight: "500",
      fontFamily: "Arial",
      textAlign: "right",
    },
    // Creative signature area
    {
      type: "rect",
      left: 300,
      top: 490,
      width: 200,
      height: 30,
      fill: "transparent",
      stroke: "#0891b2",
      strokeWidth: 1,
      strokeDashArray: [5, 5],
    },
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 495,
      width: 200,
      fill: "#0891b2",
      text: "Creative Director",
      fontSize: 12,
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Artistic bottom elements
    {
      type: "circle",
      left: 100,
      top: 520,
      radius: 8,
      fill: "#fbbf24",
      opacity: 0.4,
    },
    {
      type: "triangle",
      left: 680,
      top: 520,
      width: 16,
      height: 16,
      fill: "#06b6d4",
      opacity: 0.4,
    },
  ],
  background: "#fef7ed",
};
