export const elegantTemplate = {
  version: "5.3.0",
  objects: [
    // Top decorative border
    {
      type: "rect",
      left: 50,
      top: 30,
      width: 700,
      height: 2,
      fill: "#d4d4d8",
    },
    {
      type: "rect",
      left: 50,
      top: 35,
      width: 700,
      height: 1,
      fill: "#a1a1aa",
    },
    // Bottom decorative border
    {
      type: "rect",
      left: 50,
      top: 530,
      width: 700,
      height: 2,
      fill: "#d4d4d8",
    },
    {
      type: "rect",
      left: 50,
      top: 535,
      width: 700,
      height: 1,
      fill: "#a1a1aa",
    },
    // Left decorative elements
    {
      type: "circle",
      left: 30,
      top: 50,
      radius: 8,
      fill: "#6366f1",
    },
    {
      type: "circle",
      left: 30,
      top: 80,
      radius: 5,
      fill: "#8b5cf6",
      opacity: 0.7,
    },
    {
      type: "circle",
      left: 30,
      top: 100,
      radius: 3,
      fill: "#06b6d4",
      opacity: 0.5,
    },
    // Right decorative elements
    {
      type: "circle",
      left: 762,
      top: 466,
      radius: 8,
      fill: "#6366f1",
    },
    {
      type: "circle",
      left: 762,
      top: 486,
      radius: 5,
      fill: "#8b5cf6",
      opacity: 0.7,
    },
    {
      type: "circle",
      left: 762,
      top: 506,
      radius: 3,
      fill: "#06b6d4",
      opacity: 0.5,
    },
    // Certificate header
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 60,
      width: 600,
      fill: "#18181b",
      text: "CERTIFICATE",
      fontSize: 42,
      fontWeight: "300",
      fontFamily: "Arial",
      textAlign: "center",
      letterSpacing: 12,
    },
    // Elegant subtitle
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 110,
      width: 500,
      fill: "#6366f1",
      text: "of Excellence",
      fontSize: 28,
      fontWeight: "300",
      fontFamily: "Arial",
      textAlign: "center",
      letterSpacing: 3,
      fontStyle: "italic",
    },
    // Decorative line under title
    {
      type: "rect",
      left: 300,
      top: 150,
      width: 200,
      height: 1,
      fill: "#d4d4d8",
    },
    // Presented to text
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 170,
      width: 400,
      fill: "#52525b",
      text: "This certifies that",
      fontSize: 16,
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Recipient name
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 200,
      width: 600,
      fill: "#18181b",
      text: "RECIPIENT NAME",
      fontSize: 36,
      fontWeight: "400",
      fontFamily: "Arial",
      textAlign: "center",
      letterSpacing: 2,
    },
    // Elegant underline
    {
      type: "rect",
      left: 250,
      top: 245,
      width: 300,
      height: 1,
      fill: "#6366f1",
    },
    // Achievement description
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 270,
      width: 650,
      fill: "#52525b",
      text: "has demonstrated exceptional proficiency and successfully completed",
      fontSize: 16,
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Course name
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 300,
      width: 600,
      fill: "#6366f1",
      text: "Advanced Professional Development Program",
      fontSize: 22,
      fontWeight: "500",
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Achievement details
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 335,
      width: 500,
      fill: "#71717a",
      text: "with distinction and outstanding performance",
      fontSize: 14,
      fontFamily: "Arial",
      textAlign: "center",
      fontStyle: "italic",
    },
    // Date
    {
      type: "textbox",
      originX: "left",
      left: 100,
      top: 420,
      width: 200,
      fill: "#71717a",
      text: "Date of Completion",
      fontSize: 12,
      fontFamily: "Arial",
      textAlign: "left",
    },
    {
      type: "textbox",
      originX: "left",
      left: 100,
      top: 440,
      width: 200,
      fill: "#18181b",
      text: "March 15, 2024",
      fontSize: 16,
      fontWeight: "500",
      fontFamily: "Arial",
      textAlign: "left",
    },
    // Certificate number
    {
      type: "textbox",
      originX: "right",
      left: 700,
      top: 420,
      width: 200,
      fill: "#71717a",
      text: "Certificate No.",
      fontSize: 12,
      fontFamily: "Arial",
      textAlign: "right",
    },
    {
      type: "textbox",
      originX: "right",
      left: 700,
      top: 440,
      width: 200,
      fill: "#18181b",
      text: "ELG-2024-0089",
      fontSize: 16,
      fontWeight: "500",
      fontFamily: "Arial",
      textAlign: "right",
    },
    // Signature line
    {
      type: "line",
      x1: 0,
      y1: 0,
      x2: 150,
      y2: 0,
      left: 325,
      top: 480,
      stroke: "#d4d4d8",
      strokeWidth: 1,
    },
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 490,
      width: 150,
      fill: "#71717a",
      text: "Director of Education",
      fontSize: 12,
      fontFamily: "Arial",
      textAlign: "center",
    },
  ],
  background: "#ffffff",
};
