export const floralCornerSvg = `data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMDAgMTAwIj48cGF0aCBkPSJNNTAsMEMyMi40LDAsMCwyMi40LDAsNTBjMCwxMy44LDExLjIsMjUsMjUsMjVjMTMuOCwwLDI1LTExLjIsMjUtMjVjMC0xMy44LTExLjItMjUtMjUtMjV6IE0yNSw2Mi41Yy02LjksMC0xMi41LTUuNi0xMi41LTEyLjVzNS42LTEyLjUsMTIuNS0xMi41czEyLjUsNS42LDEyLjUsMTIuNVMzMS45LDYyLjUsMjUsNjIuNXoiIGZpbGw9IiM4YmMzNDkiLz48cGF0aCBkPSJNMTAwLDUwYzAtMjcuNi0yMi40LTUwLTUwLTUwcy01MCwyMi40LTUwLDUwYzAsMTMuOCwxMS4yLDI1LDI1LDI1czI1LTExLjIsMjUtMjVjMC0xMy44LTExLjItMjUtMjUtMjVzLTI1LDExLjItMjUsMjVjMCw2LjksNS42LDEyLjUsMTIuNSwxMi41czEyLjUtNS42LDEyLjUtMTIuNVM1Ni45LDM3LjUsNTAsMzcuNVMzNy41LDQzLjEsMzcuNSw1MHM1LjYsMTIuNSwxMi41LDEyLjVTNzUsNTYuOSw3NSw1MFM2OC4xLDM3LjUsNjAuNSwzNy41Yy02LjksMC0xMi41LDUuNi0xMi41LDEyLjVjMCw2LjksNS42LDEyLjUsMTIuNSwxMi41YzYuOSwwLDEyLjUtNS42LDEyLjUtMTIuNVM5My4xLDM3LjUsODYuNSwzNy41Yy02LjksMC0xMi41LDUuNi0xMi41LDEyLjVjMCw2LjksNS42LDEyLjUsMTIuNSwxMi41YzYuOSwwLDEyLjUtNS42LDEyLjUtMTIuNVMxMDYuOSwzNy41LDEwMCwzNy41eiIgZmlsbD0iIzRjYWY1MEAiLz48L3N2Zz4=`;

export const floralTemplate = {
  version: "5.3.0",
  background: "#FFFBF5",
  objects: [
    {
      type: "image",
      src: floralCornerSvg,
      left: 30,
      top: 30,
      scaleX: 0.8,
      scaleY: 0.8,
    },
    {
      type: "image",
      src: floralCornerSvg,
      left: 770,
      top: 30,
      scaleX: 0.8,
      scaleY: 0.8,
      angle: 90,
      originX: "center",
      originY: "center",
    },
    {
      type: "image",
      src: floralCornerSvg,
      left: 770,
      top: 536,
      scaleX: 0.8,
      scaleY: 0.8,
      angle: 180,
      originX: "center",
      originY: "center",
    },
    {
      type: "image",
      src: floralCornerSvg,
      left: 30,
      top: 536,
      scaleX: 0.8,
      scaleY: 0.8,
      angle: 270,
      originX: "center",
      originY: "center",
    },
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 80,
      width: 600,
      fill: "#5D4037",
      text: "Certificate of Appreciation",
      fontSize: 55,
      fontWeight: "bold",
      fontFamily: "Georgia",
      textAlign: "center",
    },
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 180,
      width: 300,
      fill: "#795548",
      text: "IS PROUDLY PRESENTED TO",
      fontSize: 20,
      fontFamily: "Georgia",
      textAlign: "center",
    },
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 240,
      width: 500,
      fill: "#3E2723",
      text: "[Recipient Name]",
      fontSize: 48,
      fontFamily: "Times New Roman",
      textAlign: "center",
    },
    {
      type: "rect",
      left: 150,
      top: 320,
      width: 500,
      height: 1,
      fill: "#A1887F",
    },
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 350,
      width: 550,
      fill: "#6D4C41",
      text: "For outstanding contribution and dedicated service. Your efforts have made a significant impact.",
      fontSize: 18,
      fontFamily: "Georgia",
      textAlign: "center",
    },
  ],
};
