export const luxuryTemplate = {
  version: "5.3.0",
  objects: [
    // Luxury cream background
    {
      type: "rect",
      left: 0,
      top: 0,
      width: 800,
      height: 566,
      fill: "#fefcf3",
    },
    // Golden border frame
    {
      type: "rect",
      left: 20,
      top: 20,
      width: 760,
      height: 526,
      fill: "transparent",
      stroke: "#d4af37",
      strokeWidth: 3,
    },
    {
      type: "rect",
      left: 30,
      top: 30,
      width: 740,
      height: 506,
      fill: "transparent",
      stroke: "#d4af37",
      strokeWidth: 1,
    },
    // Corner decorations
    {
      type: "rect",
      left: 40,
      top: 40,
      width: 30,
      height: 3,
      fill: "#d4af37",
    },
    {
      type: "rect",
      left: 40,
      top: 40,
      width: 3,
      height: 30,
      fill: "#d4af37",
    },
    {
      type: "rect",
      left: 730,
      top: 40,
      width: 30,
      height: 3,
      fill: "#d4af37",
    },
    {
      type: "rect",
      left: 757,
      top: 40,
      width: 3,
      height: 30,
      fill: "#d4af37",
    },
    {
      type: "rect",
      left: 40,
      top: 523,
      width: 30,
      height: 3,
      fill: "#d4af37",
    },
    {
      type: "rect",
      left: 40,
      top: 496,
      width: 3,
      height: 30,
      fill: "#d4af37",
    },
    {
      type: "rect",
      left: 730,
      top: 523,
      width: 30,
      height: 3,
      fill: "#d4af37",
    },
    {
      type: "rect",
      left: 757,
      top: 496,
      width: 3,
      height: 30,
      fill: "#d4af37",
    },
    // Ornamental elements
    {
      type: "circle",
      left: 380,
      top: 55,
      radius: 15,
      fill: "transparent",
      stroke: "#d4af37",
      strokeWidth: 2,
    },
    {
      type: "circle",
      left: 405,
      top: 55,
      radius: 15,
      fill: "transparent",
      stroke: "#d4af37",
      strokeWidth: 2,
    },
    // Luxury title
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 90,
      width: 650,
      fill: "#8b4513",
      text: "CERTIFICATE",
      fontSize: 44,
      fontWeight: "400",
      fontFamily: "Times New Roman",
      textAlign: "center",
      letterSpacing: 6,
    },
    // Elegant subtitle
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 140,
      width: 500,
      fill: "#d4af37",
      text: "~ of Distinguished Achievement ~",
      fontSize: 20,
      fontWeight: "400",
      fontFamily: "Times New Roman",
      textAlign: "center",
      fontStyle: "italic",
      letterSpacing: 1,
    },
    // Decorative flourish
    {
      type: "rect",
      left: 300,
      top: 175,
      width: 200,
      height: 1,
      fill: "#d4af37",
    },
    {
      type: "circle",
      left: 395,
      top: 172,
      radius: 3,
      fill: "#d4af37",
    },
    {
      type: "circle",
      left: 402,
      top: 172,
      radius: 3,
      fill: "#d4af37",
    },
    // Presented to section
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 200,
      width: 400,
      fill: "#5d4e37",
      text: "This is proudly presented to",
      fontSize: 16,
      fontFamily: "Times New Roman",
      textAlign: "center",
      fontStyle: "italic",
    },
    // Recipient name with luxury styling
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 230,
      width: 600,
      fill: "#8b4513",
      text: "RECIPIENT NAME",
      fontSize: 38,
      fontWeight: "bold",
      fontFamily: "Times New Roman",
      textAlign: "center",
      letterSpacing: 2,
    },
    // Ornate underline
    {
      type: "rect",
      left: 180,
      top: 275,
      width: 440,
      height: 2,
      fill: "#d4af37",
    },
    {
      type: "circle",
      left: 175,
      top: 272,
      radius: 4,
      fill: "#d4af37",
    },
    {
      type: "circle",
      left: 621,
      top: 272,
      radius: 4,
      fill: "#d4af37",
    },
    // Achievement text
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 300,
      width: 650,
      fill: "#5d4e37",
      text: "for outstanding achievement and successful completion of",
      fontSize: 16,
      fontFamily: "Times New Roman",
      textAlign: "center",
    },
    // Program name
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 330,
      width: 600,
      fill: "#8b4513",
      text: "Executive Master Class Series",
      fontSize: 26,
      fontWeight: "bold",
      fontFamily: "Times New Roman",
      textAlign: "center",
      letterSpacing: 1,
    },
    // Achievement details
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 365,
      width: 500,
      fill: "#6b5b47",
      text: "with exceptional performance and dedication",
      fontSize: 15,
      fontFamily: "Times New Roman",
      textAlign: "center",
      fontStyle: "italic",
    },
    // Date section with luxury styling
    {
      type: "textbox",
      originX: "left",
      left: 80,
      top: 420,
      width: 200,
      fill: "#6b5b47",
      text: "AWARDED ON",
      fontSize: 12,
      fontWeight: "600",
      fontFamily: "Times New Roman",
      textAlign: "left",
      letterSpacing: 2,
    },
    {
      type: "textbox",
      originX: "left",
      left: 80,
      top: 440,
      width: 200,
      fill: "#8b4513",
      text: "March 15th, 2024",
      fontSize: 16,
      fontWeight: "500",
      fontFamily: "Times New Roman",
      textAlign: "left",
    },
    // Certificate number
    {
      type: "textbox",
      originX: "right",
      left: 720,
      top: 420,
      width: 200,
      fill: "#6b5b47",
      text: "CERTIFICATE NO.",
      fontSize: 12,
      fontWeight: "600",
      fontFamily: "Times New Roman",
      textAlign: "right",
      letterSpacing: 2,
    },
    {
      type: "textbox",
      originX: "right",
      left: 720,
      top: 440,
      width: 200,
      fill: "#8b4513",
      text: "LUX-2024-0890",
      fontSize: 16,
      fontWeight: "500",
      fontFamily: "Times New Roman",
      textAlign: "right",
    },
    // Signature section
    {
      type: "line",
      x1: 0,
      y1: 0,
      x2: 160,
      y2: 0,
      left: 320,
      top: 490,
      stroke: "#d4af37",
      strokeWidth: 2,
    },
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 500,
      width: 160,
      fill: "#6b5b47",
      text: "Executive Director",
      fontSize: 13,
      fontWeight: "500",
      fontFamily: "Times New Roman",
      textAlign: "center",
    },
    // Bottom luxury accent
    {
      type: "rect",
      left: 350,
      top: 530,
      width: 100,
      height: 2,
      fill: "#d4af37",
    },
  ],
  background: "#ffffff",
};
