export const minimalistTemplate = {
  version: "5.3.0",
  objects: [
    // Top accent line
    {
      type: "rect",
      left: 0,
      top: 0,
      width: 800,
      height: 4,
      fill: "#000000",
    },
    // Simple title
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 80,
      width: 600,
      fill: "#000000",
      text: "CERTIFICATE",
      fontSize: 48,
      fontWeight: "300",
      fontFamily: "Arial",
      textAlign: "center",
      letterSpacing: 8,
    },
    // Minimalist line under title
    {
      type: "rect",
      left: 350,
      top: 140,
      width: 100,
      height: 1,
      fill: "#000000",
    },
    // Clean subtitle
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 160,
      width: 400,
      fill: "#404040",
      text: "This is to certify that",
      fontSize: 18,
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Recipient name
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 200,
      width: 600,
      fill: "#000000",
      text: "RECIPIENT NAME",
      fontSize: 40,
      fontWeight: "400",
      fontFamily: "Arial",
      textAlign: "center",
      letterSpacing: 1,
    },
    // Simple underline
    {
      type: "rect",
      left: 200,
      top: 250,
      width: 400,
      height: 1,
      fill: "#000000",
    },
    // Achievement text
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 270,
      width: 600,
      fill: "#404040",
      text: "has successfully completed the requirements for",
      fontSize: 16,
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Course name
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 300,
      width: 500,
      fill: "#000000",
      text: "Professional Excellence Program",
      fontSize: 24,
      fontWeight: "500",
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Date section
    {
      type: "textbox",
      originX: "left",
      left: 100,
      top: 400,
      width: 200,
      fill: "#404040",
      text: "Date",
      fontSize: 14,
      fontFamily: "Arial",
      textAlign: "left",
    },
    {
      type: "textbox",
      originX: "left",
      left: 100,
      top: 420,
      width: 200,
      fill: "#000000",
      text: "March 15, 2024",
      fontSize: 16,
      fontFamily: "Arial",
      textAlign: "left",
    },
    // Certificate ID
    {
      type: "textbox",
      originX: "right",
      left: 700,
      top: 400,
      width: 200,
      fill: "#404040",
      text: "Certificate ID",
      fontSize: 14,
      fontFamily: "Arial",
      textAlign: "right",
    },
    {
      type: "textbox",
      originX: "right",
      left: 700,
      top: 420,
      width: 200,
      fill: "#000000",
      text: "MIN-2024-0234",
      fontSize: 16,
      fontFamily: "Arial",
      textAlign: "right",
    },
    // Signature line
    {
      type: "line",
      x1: 0,
      y1: 0,
      x2: 120,
      y2: 0,
      left: 340,
      top: 480,
      stroke: "#000000",
      strokeWidth: 1,
    },
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 490,
      width: 120,
      fill: "#404040",
      text: "Authorized Signature",
      fontSize: 12,
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Bottom accent line
    {
      type: "rect",
      left: 0,
      top: 562,
      width: 800,
      height: 4,
      fill: "#000000",
    },
  ],
  background: "#ffffff",
};
