export const modernTemplate = {
  version: "5.3.0",
  objects: [
    { type: "rect", left: 50, top: 40, width: 700, height: 2, fill: "#3498db" },
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 80,
      width: 600,
      fill: "#2c3e50",
      text: "CERTIFICATE OF ACHIEVEMENT",
      fontSize: 60,
      fontWeight: "bold",
      fontFamily: "Georgia",
      textAlign: "center",
    },
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 200,
      width: 300,
      fill: "#34495e",
      text: "PROUDLY PRESENTED TO",
      fontSize: 22,
      fontFamily: "Arial",
      textAlign: "center",
    },
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 250,
      width: 500,
      fill: "#3498db",
      text: "Recipient Name",
      fontSize: 50,
      fontWeight: "bold",
      fontFamily: "Times New Roman",
      textAlign: "center",
    },
    {
      type: "rect",
      left: 50,
      top: 520,
      width: 700,
      height: 2,
      fill: "#3498db",
    },
  ],
  background: "#ffffff",
};
