export const modernTemplate = {
  version: "5.3.0",
  objects: [
    // Background gradient effect (using rectangles)
    {
      type: "rect",
      left: 0,
      top: 0,
      width: 800,
      height: 100,
      fill: "#2c3e50",
      opacity: 0.05,
    },
    {
      type: "rect",
      left: 0,
      top: 466,
      width: 800,
      height: 100,
      fill: "#2c3e50",
      opacity: 0.05,
    },
    // Left accent bar
    {
      type: "rect",
      left: 0,
      top: 0,
      width: 8,
      height: 566,
      fill: "#3498db",
    },
    // Right accent bar
    {
      type: "rect",
      left: 792,
      top: 0,
      width: 8,
      height: 566,
      fill: "#3498db",
    },
    // Header line
    {
      type: "rect",
      left: 80,
      top: 60,
      width: 640,
      height: 3,
      fill: "#3498db",
    },
    // Main title
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 75,
      width: 700,
      fill: "#2c3e50",
      text: "CERTIFICATE",
      fontSize: 52,
      fontWeight: "300",
      fontFamily: "Arial",
      textAlign: "center",
      letterSpacing: 8,
    },
    // Subtitle
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 130,
      width: 500,
      fill: "#7f8c8d",
      text: "OF PROFESSIONAL ACHIEVEMENT",
      fontSize: 18,
      fontWeight: "400",
      fontFamily: "Arial",
      textAlign: "center",
      letterSpacing: 2,
    },
    // Presented to text
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 170,
      width: 400,
      fill: "#34495e",
      text: "This is to certify that",
      fontSize: 16,
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Recipient name
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 200,
      width: 600,
      fill: "#2c3e50",
      text: "RECIPIENT NAME",
      fontSize: 38,
      fontWeight: "bold",
      fontFamily: "Arial",
      textAlign: "center",
      letterSpacing: 2,
    },
    // Underline for name
    {
      type: "rect",
      left: 200,
      top: 250,
      width: 400,
      height: 2,
      fill: "#3498db",
    },
    // Achievement description
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 270,
      width: 650,
      fill: "#34495e",
      text: "has successfully completed the requirements and demonstrated",
      fontSize: 16,
      fontFamily: "Arial",
      textAlign: "center",
    },
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 295,
      width: 650,
      fill: "#34495e",
      text: "exceptional competency in",
      fontSize: 16,
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Course/Program name
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 325,
      width: 600,
      fill: "#3498db",
      text: "Advanced Digital Marketing",
      fontSize: 24,
      fontWeight: "bold",
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Completion details
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 365,
      width: 500,
      fill: "#7f8c8d",
      text: "80 Hours • 12 Modules • Final Project",
      fontSize: 14,
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Date section
    {
      type: "textbox",
      originX: "left",
      left: 100,
      top: 420,
      width: 200,
      fill: "#7f8c8d",
      text: "COMPLETION DATE",
      fontSize: 12,
      fontWeight: "bold",
      fontFamily: "Arial",
      textAlign: "left",
      letterSpacing: 1,
    },
    {
      type: "textbox",
      originX: "left",
      left: 100,
      top: 440,
      width: 200,
      fill: "#2c3e50",
      text: "March 15, 2024",
      fontSize: 16,
      fontWeight: "500",
      fontFamily: "Arial",
      textAlign: "left",
    },
    // Grade/Score section
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 420,
      width: 200,
      fill: "#7f8c8d",
      text: "FINAL SCORE",
      fontSize: 12,
      fontWeight: "bold",
      fontFamily: "Arial",
      textAlign: "center",
      letterSpacing: 1,
    },
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 440,
      width: 200,
      fill: "#27ae60",
      text: "95%",
      fontSize: 20,
      fontWeight: "bold",
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Certificate ID section
    {
      type: "textbox",
      originX: "right",
      left: 700,
      top: 420,
      width: 200,
      fill: "#7f8c8d",
      text: "CERTIFICATE ID",
      fontSize: 12,
      fontWeight: "bold",
      fontFamily: "Arial",
      textAlign: "right",
      letterSpacing: 1,
    },
    {
      type: "textbox",
      originX: "right",
      left: 700,
      top: 440,
      width: 200,
      fill: "#2c3e50",
      text: "MDC-2024-0157",
      fontSize: 16,
      fontWeight: "500",
      fontFamily: "Arial",
      textAlign: "right",
    },
    // Signature section
    {
      type: "line",
      x1: 0,
      y1: 0,
      x2: 120,
      y2: 0,
      left: 240,
      top: 500,
      stroke: "#bdc3c7",
      strokeWidth: 1,
    },
    {
      type: "line",
      x1: 0,
      y1: 0,
      x2: 120,
      y2: 0,
      left: 440,
      top: 500,
      stroke: "#bdc3c7",
      strokeWidth: 1,
    },
    {
      type: "textbox",
      originX: "center",
      left: 300,
      top: 510,
      width: 120,
      fill: "#7f8c8d",
      text: "Program Director",
      fontSize: 12,
      fontFamily: "Arial",
      textAlign: "center",
    },
    {
      type: "textbox",
      originX: "center",
      left: 500,
      top: 510,
      width: 120,
      fill: "#7f8c8d",
      text: "Lead Instructor",
      fontSize: 12,
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Footer line
    {
      type: "rect",
      left: 80,
      top: 545,
      width: 640,
      height: 3,
      fill: "#3498db",
    },
  ],
  background: "#ffffff",
};
