export const playfulTemplate = {
  version: "5.3.0",
  objects: [
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 70,
      width: 500,
      fill: "#e67e22",
      text: "Awesome Award!",
      fontSize: 80,
      fontWeight: "bold",
      fontFamily: "Verdana",
      textAlign: "center",
    },
    {
      type: "rect",
      left: 100,
      top: 180,
      width: 600,
      height: 10,
      fill: "#2ecc71",
    },
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 220,
      width: 300,
      fill: "#8e44ad",
      text: "This award goes to...",
      fontSize: 22,
      fontFamily: "Courier New",
      textAlign: "center",
    },
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 270,
      width: 500,
      fill: "#3498db",
      text: "Superstar Name",
      fontSize: 50,
      fontWeight: "bold",
      fontFamily: "Verdana",
      textAlign: "center",
    },
    {
      type: "rect",
      left: 100,
      top: 450,
      width: 600,
      height: 10,
      fill: "#f1c40f",
    },
  ],
  background: "#ecf0f1",
};
