export const playfulTemplate = {
  version: "5.3.0",
  objects: [
    // Fun background elements
    {
      type: "circle",
      left: 50,
      top: 50,
      radius: 25,
      fill: "#ff6b6b",
      opacity: 0.3,
    },
    {
      type: "circle",
      left: 720,
      top: 80,
      radius: 20,
      fill: "#4ecdc4",
      opacity: 0.4,
    },
    {
      type: "circle",
      left: 680,
      top: 480,
      radius: 30,
      fill: "#45b7d1",
      opacity: 0.3,
    },
    {
      type: "circle",
      left: 80,
      top: 450,
      radius: 18,
      fill: "#f39c12",
      opacity: 0.4,
    },
    // Star decorations
    {
      type: "path",
      path: "M 25 0 L 31 19 L 50 19 L 35 31 L 41 50 L 25 38 L 9 50 L 15 31 L 0 19 L 19 19 Z",
      left: 120,
      top: 100,
      fill: "#ffd93d",
      scaleX: 0.6,
      scaleY: 0.6,
      opacity: 0.8,
    },
    {
      type: "path",
      path: "M 25 0 L 31 19 L 50 19 L 35 31 L 41 50 L 25 38 L 9 50 L 15 31 L 0 19 L 19 19 Z",
      left: 650,
      top: 120,
      fill: "#ff6b6b",
      scaleX: 0.4,
      scaleY: 0.4,
      opacity: 0.7,
    },
    {
      type: "path",
      path: "M 25 0 L 31 19 L 50 19 L 35 31 L 41 50 L 25 38 L 9 50 L 15 31 L 0 19 L 19 19 Z",
      left: 100,
      top: 380,
      fill: "#6c5ce7",
      scaleX: 0.5,
      scaleY: 0.5,
      opacity: 0.6,
    },
    // Colorful top border
    {
      type: "rect",
      left: 0,
      top: 0,
      width: 800,
      height: 15,
      fill: "#ff6b6b",
    },
    {
      type: "rect",
      left: 0,
      top: 15,
      width: 800,
      height: 10,
      fill: "#4ecdc4",
    },
    {
      type: "rect",
      left: 0,
      top: 25,
      width: 800,
      height: 8,
      fill: "#45b7d1",
    },
    // Colorful bottom border
    {
      type: "rect",
      left: 0,
      top: 533,
      width: 800,
      height: 8,
      fill: "#45b7d1",
    },
    {
      type: "rect",
      left: 0,
      top: 541,
      width: 800,
      height: 10,
      fill: "#4ecdc4",
    },
    {
      type: "rect",
      left: 0,
      top: 551,
      width: 800,
      height: 15,
      fill: "#ff6b6b",
    },
    // Main title
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 60,
      width: 650,
      fill: "#2d3436",
      text: "🎉 SUPER STAR AWARD 🎉",
      fontSize: 42,
      fontWeight: "bold",
      fontFamily: "Comic Sans MS",
      textAlign: "center",
    },
    // Fun subtitle
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 115,
      width: 600,
      fill: "#6c5ce7",
      text: "For Being Absolutely Amazing!",
      fontSize: 20,
      fontWeight: "bold",
      fontFamily: "Arial",
      textAlign: "center",
      fontStyle: "italic",
    },
    // Colorful divider
    {
      type: "rect",
      left: 150,
      top: 150,
      width: 500,
      height: 6,
      fill: "#ffd93d",
      rx: 3,
      ry: 3,
    },
    // Presented to text
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 175,
      width: 400,
      fill: "#2d3436",
      text: "This awesome certificate is presented to",
      fontSize: 16,
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Recipient name with fun styling
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 205,
      width: 600,
      fill: "#e17055",
      text: "CHAMPION NAME",
      fontSize: 36,
      fontWeight: "bold",
      fontFamily: "Arial",
      textAlign: "center",
      textDecoration: "underline",
    },
    // Achievement description
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 260,
      width: 650,
      fill: "#2d3436",
      text: "for outstanding performance and exceptional dedication in",
      fontSize: 16,
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Activity/Course name
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 285,
      width: 600,
      fill: "#00b894",
      text: "Creative Learning Adventures",
      fontSize: 26,
      fontWeight: "bold",
      fontFamily: "Arial",
      textAlign: "center",
      fontStyle: "italic",
    },
    // Fun achievement badges
    {
      type: "circle",
      left: 180,
      top: 340,
      radius: 35,
      fill: "#fd79a8",
      opacity: 0.8,
    },
    {
      type: "textbox",
      originX: "center",
      left: 215,
      top: 360,
      width: 70,
      fill: "white",
      text: "100%\nComplete",
      fontSize: 12,
      fontWeight: "bold",
      fontFamily: "Arial",
      textAlign: "center",
    },
    {
      type: "circle",
      left: 350,
      top: 340,
      radius: 35,
      fill: "#fdcb6e",
      opacity: 0.8,
    },
    {
      type: "textbox",
      originX: "center",
      left: 385,
      top: 365,
      width: 70,
      fill: "white",
      text: "Top\nPerformer",
      fontSize: 12,
      fontWeight: "bold",
      fontFamily: "Arial",
      textAlign: "center",
    },
    {
      type: "circle",
      left: 520,
      top: 340,
      radius: 35,
      fill: "#a29bfe",
      opacity: 0.8,
    },
    {
      type: "textbox",
      originX: "center",
      left: 555,
      top: 365,
      width: 70,
      fill: "white",
      text: "Team\nPlayer",
      fontSize: 12,
      fontWeight: "bold",
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Date and details
    {
      type: "textbox",
      originX: "left",
      left: 120,
      top: 430,
      width: 200,
      fill: "#636e72",
      text: "Awarded on:",
      fontSize: 14,
      fontFamily: "Arial",
      textAlign: "left",
    },
    {
      type: "textbox",
      originX: "left",
      left: 120,
      top: 450,
      width: 200,
      fill: "#2d3436",
      text: "April 20, 2024",
      fontSize: 16,
      fontWeight: "bold",
      fontFamily: "Arial",
      textAlign: "left",
    },
    // Fun fact or score
    {
      type: "textbox",
      originX: "right",
      left: 680,
      top: 430,
      width: 200,
      fill: "#636e72",
      text: "Fun Level Achieved:",
      fontSize: 14,
      fontFamily: "Arial",
      textAlign: "right",
    },
    {
      type: "textbox",
      originX: "right",
      left: 680,
      top: 450,
      width: 200,
      fill: "#fd79a8",
      text: "MAXIMUM! 🚀",
      fontSize: 16,
      fontWeight: "bold",
      fontFamily: "Arial",
      textAlign: "right",
    },
    // Signature area
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 485,
      width: 300,
      fill: "#636e72",
      text: "Keep being awesome! ⭐",
      fontSize: 14,
      fontFamily: "Arial",
      textAlign: "center",
      fontStyle: "italic",
    },
    // Signature line
    {
      type: "line",
      x1: 0,
      y1: 0,
      x2: 150,
      y2: 0,
      left: 325,
      top: 510,
      stroke: "#636e72",
      strokeWidth: 2,
      strokeDashArray: [5, 5],
    },
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 515,
      width: 150,
      fill: "#636e72",
      text: "Signature",
      fontSize: 12,
      fontFamily: "Arial",
      textAlign: "center",
    },
  ],
  background: "#ffeaa7",
};
