export const professionalTemplate = {
  version: "5.3.0",
  objects: [
    // Professional white background
    {
      type: "rect",
      left: 0,
      top: 0,
      width: 800,
      height: 566,
      fill: "#ffffff",
    },
    // Header section
    {
      type: "rect",
      left: 0,
      top: 0,
      width: 800,
      height: 100,
      fill: "#1f2937",
    },
    // Professional accent stripe
    {
      type: "rect",
      left: 0,
      top: 100,
      width: 800,
      height: 6,
      fill: "#059669",
    },
    // Company section
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 25,
      width: 600,
      fill: "#ffffff",
      text: "PROFESSIONAL DEVELOPMENT INSTITUTE",
      fontSize: 18,
      fontWeight: "600",
      fontFamily: "Arial",
      textAlign: "center",
      letterSpacing: 3,
    },
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 50,
      width: 500,
      fill: "#d1d5db",
      text: "Advancing Careers Through Excellence",
      fontSize: 14,
      fontFamily: "Arial",
      textAlign: "center",
      letterSpacing: 1,
    },
    // Main certificate title
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 130,
      width: 650,
      fill: "#1f2937",
      text: "PROFESSIONAL CERTIFICATE",
      fontSize: 36,
      fontWeight: "700",
      fontFamily: "Arial",
      textAlign: "center",
      letterSpacing: 4,
    },
    // Professional line
    {
      type: "rect",
      left: 200,
      top: 175,
      width: 400,
      height: 2,
      fill: "#059669",
    },
    // Achievement statement
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 195,
      width: 500,
      fill: "#374151",
      text: "This certifies that",
      fontSize: 16,
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Recipient name
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 225,
      width: 600,
      fill: "#1f2937",
      text: "RECIPIENT NAME",
      fontSize: 34,
      fontWeight: "600",
      fontFamily: "Arial",
      textAlign: "center",
      letterSpacing: 1,
    },
    // Professional underline
    {
      type: "rect",
      left: 225,
      top: 265,
      width: 350,
      height: 1,
      fill: "#059669",
    },
    // Completion statement
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 285,
      width: 650,
      fill: "#374151",
      text: "has successfully completed all requirements and demonstrated proficiency in",
      fontSize: 15,
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Program name
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 315,
      width: 600,
      fill: "#059669",
      text: "Strategic Business Management",
      fontSize: 26,
      fontWeight: "600",
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Program details
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 350,
      width: 500,
      fill: "#6b7280",
      text: "Professional Development Program • 160 Hours",
      fontSize: 14,
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Professional metrics
    {
      type: "rect",
      left: 250,
      top: 380,
      width: 300,
      height: 1,
      fill: "#d1d5db",
    },
    {
      type: "textbox",
      originX: "center",
      left: 300,
      top: 390,
      width: 100,
      fill: "#6b7280",
      text: "GPA: 3.95",
      fontSize: 12,
      fontFamily: "Arial",
      textAlign: "center",
    },
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 390,
      width: 100,
      fill: "#6b7280",
      text: "Grade: A",
      fontSize: 12,
      fontFamily: "Arial",
      textAlign: "center",
    },
    {
      type: "textbox",
      originX: "center",
      left: 500,
      top: 390,
      width: 100,
      fill: "#6b7280",
      text: "Credits: 24",
      fontSize: 12,
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Footer information
    {
      type: "rect",
      left: 0,
      top: 446,
      width: 800,
      height: 120,
      fill: "#f9fafb",
    },
    // Date section
    {
      type: "textbox",
      originX: "left",
      left: 80,
      top: 465,
      width: 200,
      fill: "#6b7280",
      text: "DATE OF COMPLETION",
      fontSize: 11,
      fontWeight: "600",
      fontFamily: "Arial",
      textAlign: "left",
      letterSpacing: 1,
    },
    {
      type: "textbox",
      originX: "left",
      left: 80,
      top: 480,
      width: 200,
      fill: "#1f2937",
      text: "March 15, 2024",
      fontSize: 15,
      fontWeight: "500",
      fontFamily: "Arial",
      textAlign: "left",
    },
    // Certificate ID
    {
      type: "textbox",
      originX: "right",
      left: 720,
      top: 465,
      width: 200,
      fill: "#6b7280",
      text: "CERTIFICATE ID",
      fontSize: 11,
      fontWeight: "600",
      fontFamily: "Arial",
      textAlign: "right",
      letterSpacing: 1,
    },
    {
      type: "textbox",
      originX: "right",
      left: 720,
      top: 480,
      width: 200,
      fill: "#1f2937",
      text: "PRO-2024-0678",
      fontSize: 15,
      fontWeight: "500",
      fontFamily: "Arial",
      textAlign: "right",
    },
    // Signature section
    {
      type: "line",
      x1: 0,
      y1: 0,
      x2: 150,
      y2: 0,
      left: 325,
      top: 515,
      stroke: "#059669",
      strokeWidth: 2,
    },
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 525,
      width: 150,
      fill: "#374151",
      text: "Program Director",
      fontSize: 12,
      fontWeight: "500",
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Professional badge
    {
      type: "rect",
      left: 600,
      top: 520,
      width: 80,
      height: 20,
      fill: "#059669",
    },
    {
      type: "textbox",
      originX: "center",
      left: 640,
      top: 523,
      width: 80,
      fill: "#ffffff",
      text: "VERIFIED",
      fontSize: 10,
      fontWeight: "600",
      fontFamily: "Arial",
      textAlign: "center",
    },
  ],
  background: "#ffffff",
};
