export const techTemplate = {
  version: "5.3.0",
  objects: [
    // Circuit-like decoration lines
    {
      type: "line",
      x1: 0,
      y1: 0,
      x2: 200,
      y2: 0,
      left: 50,
      top: 50,
      stroke: "#00d4aa",
      strokeWidth: 2,
    },
    {
      type: "line",
      x1: 0,
      y1: 0,
      x2: 0,
      y2: 50,
      left: 250,
      top: 50,
      stroke: "#00d4aa",
      strokeWidth: 2,
    },
    {
      type: "line",
      x1: 0,
      y1: 0,
      x2: 100,
      y2: 0,
      left: 250,
      top: 100,
      stroke: "#00d4aa",
      strokeWidth: 2,
    },
    // Tech nodes
    {
      type: "circle",
      left: 245,
      top: 45,
      radius: 5,
      fill: "#00d4aa",
    },
    {
      type: "circle",
      left: 245,
      top: 95,
      radius: 5,
      fill: "#00d4aa",
    },
    {
      type: "circle",
      left: 345,
      top: 95,
      radius: 5,
      fill: "#00d4aa",
    },
    // Right side circuit pattern
    {
      type: "line",
      x1: 0,
      y1: 0,
      x2: 200,
      y2: 0,
      left: 550,
      top: 516,
      stroke: "#6366f1",
      strokeWidth: 2,
    },
    {
      type: "line",
      x1: 0,
      y1: 0,
      x2: 0,
      y2: -50,
      left: 550,
      top: 516,
      stroke: "#6366f1",
      strokeWidth: 2,
    },
    {
      type: "line",
      x1: 0,
      y1: 0,
      x2: -100,
      y2: 0,
      left: 550,
      top: 466,
      stroke: "#6366f1",
      strokeWidth: 2,
    },
    // Tech nodes right
    {
      type: "circle",
      left: 545,
      top: 511,
      radius: 5,
      fill: "#6366f1",
    },
    {
      type: "circle",
      left: 545,
      top: 461,
      radius: 5,
      fill: "#6366f1",
    },
    {
      type: "circle",
      left: 445,
      top: 461,
      radius: 5,
      fill: "#6366f1",
    },
    // Glowing header effect
    {
      type: "rect",
      left: 0,
      top: 80,
      width: 800,
      height: 80,
      fill: "#1e293b",
      opacity: 0.5,
    },
    // Digital title
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 100,
      width: 650,
      fill: "#00d4aa",
      text: "DIGITAL CERTIFICATE",
      fontSize: 38,
      fontWeight: "700",
      fontFamily: "Arial",
      textAlign: "center",
      letterSpacing: 6,
    },
    // Tech subtitle
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 145,
      width: 500,
      fill: "#64748b",
      text: "Technology Excellence Program",
      fontSize: 16,
      fontFamily: "Arial",
      textAlign: "center",
      letterSpacing: 2,
    },
    // Hex pattern decoration
    {
      type: "rect",
      left: 50,
      top: 180,
      width: 10,
      height: 10,
      fill: "#6366f1",
      opacity: 0.3,
      angle: 45,
    },
    {
      type: "rect",
      left: 740,
      top: 180,
      width: 10,
      height: 10,
      fill: "#00d4aa",
      opacity: 0.3,
      angle: 45,
    },
    // Achievement section
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 200,
      width: 400,
      fill: "#cbd5e1",
      text: "This validates that",
      fontSize: 16,
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Recipient name with glow effect
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 230,
      width: 600,
      fill: "#ffffff",
      text: "RECIPIENT NAME",
      fontSize: 36,
      fontWeight: "600",
      fontFamily: "Arial",
      textAlign: "center",
      letterSpacing: 2,
    },
    // Digital underline
    {
      type: "rect",
      left: 200,
      top: 275,
      width: 400,
      height: 2,
      fill: "#00d4aa",
    },
    {
      type: "rect",
      left: 200,
      top: 278,
      width: 400,
      height: 1,
      fill: "#00d4aa",
      opacity: 0.5,
    },
    // Tech achievement text
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 300,
      width: 650,
      fill: "#cbd5e1",
      text: "has successfully mastered advanced concepts and completed",
      fontSize: 15,
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Program name
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 325,
      width: 600,
      fill: "#00d4aa",
      text: "Full-Stack Development Bootcamp",
      fontSize: 24,
      fontWeight: "600",
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Tech specs
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 355,
      width: 550,
      fill: "#64748b",
      text: "600+ Hours • 15 Projects • Industry Mentorship",
      fontSize: 13,
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Tech score display
    {
      type: "rect",
      left: 350,
      top: 380,
      width: 100,
      height: 30,
      fill: "#1e293b",
      stroke: "#00d4aa",
      strokeWidth: 1,
    },
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 385,
      width: 100,
      fill: "#00d4aa",
      text: "SCORE: 97%",
      fontSize: 12,
      fontWeight: "600",
      fontFamily: "Arial",
      textAlign: "center",
    },
    // Date section
    {
      type: "textbox",
      originX: "left",
      left: 80,
      top: 440,
      width: 200,
      fill: "#64748b",
      text: "COMPLETION DATE",
      fontSize: 11,
      fontWeight: "600",
      fontFamily: "Arial",
      textAlign: "left",
      letterSpacing: 1,
    },
    {
      type: "textbox",
      originX: "left",
      left: 80,
      top: 455,
      width: 200,
      fill: "#ffffff",
      text: "2024.03.15",
      fontSize: 14,
      fontWeight: "500",
      fontFamily: "Arial",
      textAlign: "left",
    },
    // Blockchain-style ID
    {
      type: "textbox",
      originX: "right",
      left: 720,
      top: 440,
      width: 200,
      fill: "#64748b",
      text: "BLOCKCHAIN ID",
      fontSize: 11,
      fontWeight: "600",
      fontFamily: "Arial",
      textAlign: "right",
      letterSpacing: 1,
    },
    {
      type: "textbox",
      originX: "right",
      left: 720,
      top: 455,
      width: 200,
      fill: "#ffffff",
      text: "0xTEC240315A7B9",
      fontSize: 14,
      fontWeight: "500",
      fontFamily: "Arial",
      textAlign: "right",
    },
    // Digital signature
    {
      type: "rect",
      left: 320,
      top: 490,
      width: 160,
      height: 25,
      fill: "#1e293b",
      stroke: "#6366f1",
      strokeWidth: 1,
    },
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 495,
      width: 160,
      fill: "#6366f1",
      text: "DIGITALLY VERIFIED",
      fontSize: 12,
      fontWeight: "600",
      fontFamily: "Arial",
      textAlign: "center",
    },
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 520,
      width: 160,
      fill: "#64748b",
      text: "Platform Administrator",
      fontSize: 11,
      fontFamily: "Arial",
      textAlign: "center",
    },
  ],
  background: "#0f172a",
};
