export const vintageTemplate = {
  version: "5.3.0",
  objects: [
    // Vintage paper background
    {
      type: "rect",
      left: 0,
      top: 0,
      width: 800,
      height: 566,
      fill: "#f7f3e8",
    },
    // Ornate border frame
    {
      type: "rect",
      left: 25,
      top: 25,
      width: 750,
      height: 516,
      fill: "transparent",
      stroke: "#8b4513",
      strokeWidth: 4,
    },
    {
      type: "rect",
      left: 35,
      top: 35,
      width: 730,
      height: 496,
      fill: "transparent",
      stroke: "#a0522d",
      strokeWidth: 2,
    },
    {
      type: "rect",
      left: 45,
      top: 45,
      width: 710,
      height: 476,
      fill: "transparent",
      stroke: "#cd853f",
      strokeWidth: 1,
    },
    // Corner ornaments
    {
      type: "rect",
      left: 55,
      top: 55,
      width: 40,
      height: 3,
      fill: "#8b4513",
    },
    {
      type: "rect",
      left: 55,
      top: 55,
      width: 3,
      height: 40,
      fill: "#8b4513",
    },
    {
      type: "rect",
      left: 705,
      top: 55,
      width: 40,
      height: 3,
      fill: "#8b4513",
    },
    {
      type: "rect",
      left: 742,
      top: 55,
      width: 3,
      height: 40,
      fill: "#8b4513",
    },
    {
      type: "rect",
      left: 55,
      top: 508,
      width: 40,
      height: 3,
      fill: "#8b4513",
    },
    {
      type: "rect",
      left: 55,
      top: 478,
      width: 3,
      height: 40,
      fill: "#8b4513",
    },
    {
      type: "rect",
      left: 705,
      top: 508,
      width: 40,
      height: 3,
      fill: "#8b4513",
    },
    {
      type: "rect",
      left: 742,
      top: 478,
      width: 3,
      height: 40,
      fill: "#8b4513",
    },
    // Vintage flourishes
    {
      type: "ellipse",
      left: 370,
      top: 75,
      rx: 30,
      ry: 8,
      fill: "transparent",
      stroke: "#8b4513",
      strokeWidth: 2,
    },
    {
      type: "ellipse",
      left: 370,
      top: 478,
      rx: 30,
      ry: 8,
      fill: "transparent",
      stroke: "#8b4513",
      strokeWidth: 2,
    },
    // Vintage title
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 100,
      width: 650,
      fill: "#8b4513",
      text: "CERTIFICATE",
      fontSize: 44,
      fontWeight: "bold",
      fontFamily: "Times New Roman",
      textAlign: "center",
      letterSpacing: 8,
    },
    // Decorative subtitle
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 150,
      width: 500,
      fill: "#a0522d",
      text: "~ of Distinguished Merit ~",
      fontSize: 20,
      fontWeight: "400",
      fontFamily: "Times New Roman",
      textAlign: "center",
      fontStyle: "italic",
      letterSpacing: 2,
    },
    // Ornamental divider
    {
      type: "rect",
      left: 250,
      top: 185,
      width: 100,
      height: 2,
      fill: "#cd853f",
    },
    {
      type: "circle",
      left: 395,
      top: 182,
      radius: 4,
      fill: "#8b4513",
    },
    {
      type: "rect",
      left: 450,
      top: 185,
      width: 100,
      height: 2,
      fill: "#cd853f",
    },
    // Formal presentation text
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 210,
      width: 400,
      fill: "#654321",
      text: "This is to hereby certify that",
      fontSize: 16,
      fontFamily: "Times New Roman",
      textAlign: "center",
      fontStyle: "italic",
    },
    // Recipient name with vintage styling
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 240,
      width: 600,
      fill: "#8b4513",
      text: "RECIPIENT NAME",
      fontSize: 36,
      fontWeight: "bold",
      fontFamily: "Times New Roman",
      textAlign: "center",
      letterSpacing: 2,
    },
    // Ornate underline
    {
      type: "rect",
      left: 175,
      top: 285,
      width: 450,
      height: 2,
      fill: "#8b4513",
    },
    {
      type: "circle",
      left: 170,
      top: 282,
      radius: 4,
      fill: "#cd853f",
    },
    {
      type: "circle",
      left: 626,
      top: 282,
      radius: 4,
      fill: "#cd853f",
    },
    // Achievement description
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 310,
      width: 650,
      fill: "#654321",
      text: "has demonstrated exceptional skill and successfully completed the comprehensive",
      fontSize: 15,
      fontFamily: "Times New Roman",
      textAlign: "center",
    },
    // Course name
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 340,
      width: 600,
      fill: "#8b4513",
      text: "Classical Arts & Heritage Studies",
      fontSize: 24,
      fontWeight: "bold",
      fontFamily: "Times New Roman",
      textAlign: "center",
    },
    // Vintage details
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 375,
      width: 500,
      fill: "#a0522d",
      text: "with honors and distinction",
      fontSize: 16,
      fontFamily: "Times New Roman",
      textAlign: "center",
      fontStyle: "italic",
    },
    // Date with vintage styling
    {
      type: "textbox",
      originX: "left",
      left: 90,
      top: 430,
      width: 200,
      fill: "#8b4513",
      text: "Given this day of",
      fontSize: 14,
      fontFamily: "Times New Roman",
      textAlign: "left",
      fontStyle: "italic",
    },
    {
      type: "textbox",
      originX: "left",
      left: 90,
      top: 450,
      width: 200,
      fill: "#654321",
      text: "March 15th, 2024",
      fontSize: 16,
      fontWeight: "bold",
      fontFamily: "Times New Roman",
      textAlign: "left",
    },
    // Vintage seal placeholder
    {
      type: "circle",
      left: 650,
      top: 420,
      radius: 35,
      fill: "transparent",
      stroke: "#8b4513",
      strokeWidth: 3,
    },
    {
      type: "circle",
      left: 650,
      top: 420,
      radius: 25,
      fill: "transparent",
      stroke: "#cd853f",
      strokeWidth: 1,
    },
    {
      type: "textbox",
      originX: "center",
      left: 685,
      top: 410,
      width: 70,
      fill: "#8b4513",
      text: "OFFICIAL",
      fontSize: 10,
      fontWeight: "bold",
      fontFamily: "Times New Roman",
      textAlign: "center",
    },
    {
      type: "textbox",
      originX: "center",
      left: 685,
      top: 425,
      width: 70,
      fill: "#8b4513",
      text: "SEAL",
      fontSize: 10,
      fontWeight: "bold",
      fontFamily: "Times New Roman",
      textAlign: "center",
    },
    // Signature section
    {
      type: "line",
      x1: 0,
      y1: 0,
      x2: 150,
      y2: 0,
      left: 325,
      top: 500,
      stroke: "#8b4513",
      strokeWidth: 1,
    },
    {
      type: "textbox",
      originX: "center",
      left: 400,
      top: 510,
      width: 150,
      fill: "#654321",
      text: "Dean of Studies",
      fontSize: 13,
      fontFamily: "Times New Roman",
      textAlign: "center",
      fontStyle: "italic",
    },
  ],
  background: "#f7f3e8",
};
